[template]
src   = "nginx.conf"
dest  = "/etc/nginx/nginx.conf"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "/builtdock/services",
  "/builtdock/router",
  "/builtdock/domains",
  "/builtdock/controller",
  "/builtdock/builder",
]
check_cmd  = "/app/bin/check {{ .src }}"
reload_cmd = "/usr/sbin/nginx -s reload"
