[template]
src   = "builder"
dest  = "/home/git/builder"
uid = 0
gid = 0
mode  = "0755"
keys = [
  "/builtdock/controller",
  "/builtdock/builder",
  "/builtdock/registry",
]
check_cmd = "/app/bin/check {{ .src }}"
